service: auto-backups

resources:
  Resources:
    UploadBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${opt:bucket_name}
        AccessControl: Private
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256
        VersioningConfiguration: 
          Status: Enabled
        LifecycleConfiguration:
          Rules:
            - Id: TerminationRule
              Status: Enabled
              ExpirationInDays: ${opt:expiration_days}
              NoncurrentVersionExpirationInDays: ${opt:expiration_days}

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 2000
  timeout: 900
  stage: ${opt:stage, env:STAGE, 'production'}
  region: ${opt:region, env:REGION, 'us-east-1'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
        - ssm:*
      Resource: "*"

functions:
  autobackup:
    handler: index.handler
    environment:
      S3_BUCKET_NAME: ${opt:bucket_name}
      SPACE_ENV: ${ssm:/${opt:stage}/contentful/environment}
      SPACE_ID: ${ssm:/${opt:stage}/contentful/space_id}
      MANAGEMENT_TOKEN: ${ssm:/${opt:stage}/contentful/cms_authorization_token}
    events: 
      - schedule: ${opt:schedule}                
